name: fonts_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: "MyHelveticaNeue"
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeue Thin.ttf
          weight: 400
        - asset: assets/fonts/helvetica/HelveticaNeue BlackCond.ttf
          weight: 600
        - asset: assets/fonts/helvetica/HelveticaNeue BlackCond.ttf
          weight: 700
